spring:
  application:
    name: employee-service

  datasource:
    url: "jdbc:mysql://localhost:3306/employeedb"
    username: admin1
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

